options:
  docker: true

pipelines:
  default:
    - step:
        image: node:8-alpine
        caches:
          - node
        script:
          - yarn install
          - yarn run build
          - yarn run test

  custom:
    build:dockerhub:
      - step:
          image: node:8-alpine
          script:
            - export DOCKER_IMAGE_NAME=$DOCKER_REPOSITORY_NAME:$BITBUCKET_COMMIT

            - yarn global add docker-image-exists
            - if docker-image-exists -q -r $DOCKER_IMAGE_NAME -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD; then export DOCKER_IMAGE_EXISTS=1; fi

            - if [[ $DOCKER_IMAGE_EXISTS -ne 1 ]]; then docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD; fi
            - if [[ $DOCKER_IMAGE_EXISTS -ne 1 ]]; then docker build -t $DOCKER_IMAGE_NAME . ; fi
            - if [[ $DOCKER_IMAGE_EXISTS -ne 1 ]]; then docker push $DOCKER_IMAGE_NAME; fi

    build:aws:
      - step:
          image: garland/aws-cli-docker
          script:
            - export AWS_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_REPOSITORY_NAME
            - export DOCKER_IMAGE_NAME=$AWS_REPOSITORY_URI:$BITBUCKET_COMMIT

            - $(aws ecr get-login --no-include-email --region $AWS_REGION)
            - docker build -t $DOCKER_IMAGE_NAME .
            - docker push $DOCKER_IMAGE_NAME
